parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # ---- MongoDB pour les sessions ----
    MongoDB\Client:
        arguments:
            $uri: '%env(MONGODB_URL)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler:
        arguments:
            - '@MongoDB\Client'
            - { database: '%env(MONGODB_DB)%', collection: 'sessions' }